### ISSUE TITLE
Usage with static assets?

### ISSUE THREAD

**Issue by FoxxMD** [christian-bromann/docusaurus-theme-github-codeblock#175]
Would it be possible to use this plugin with [static assets](https://docusaurus.io/docs/static-assets) so that I can reference my own hosted files rather than having to use github?

**Comment by christian-bromann** [comment]
Right now it is hard coded to GitHub but it is surely possible to allow static assets too. Any contribution would be appreciated!

**Comment by FoxxMD** [comment]
It turns out this is basically built in to docusaurus by [importing code snippets!](https://docusaurus.io/docs/markdown-features/react#importing-code-snippets)

Thanks for the quick response though.
