### ISSUE TITLE
Breaks with 3.0.0-alpha.0

### ISSUE THREAD

**Issue by homotechsual** [christian-bromann/docusaurus-theme-github-codeblock#49]
Just a heads up/forward thinking note that this breaks on 3.0.0-alpha.0 so likely requires updates (and probably separate branch / major version bump) for v3 compatibility.

**Comment by slorber** [comment]
@christian-bromann Docusaurus v3 doesn't parse the code block metastring anymore and does not inject `props.reference = true`

This is a subtle change coming with MDX v2

To support both v2/v3 you can use this test in your `WrappedComponent`:

```js
function hasReferenceMeta(props) {
    return (props.reference || props.metastring?.split(' ').includes('reference'))
}
```

![CleanShot 2023-11-30 at 17 46 02](https://github.com/christian-bromann/docusaurus-theme-github-codeblock/assets/749374/7bb6c8ab-a065-4126-a04d-4d38123fae8b)


--- 

Side note: I suggest using a better example in your readme because your file does not contain the start/end lines. This mislead me to think there was another bug to solve while the fetched code was just an empty string.

````
```js reference
https://github.com/christian-bromann/docusaurus-theme-github-codeblock/blob/main/src/theme/ReferenceCodeBlock/index.tsx#L105-L108
```
````

![CleanShot 2023-11-30 at 17 47 37](https://github.com/christian-bromann/docusaurus-theme-github-codeblock/assets/749374/19d051d5-bdd0-4b3b-b52d-9898ad8dbb16)

**Comment by slorber** [comment]
Temporary workaround until fixed, copy this file in `src/theme/CodeBlock.js':


```js
import React from 'react';
import ReferenceCodeBlock from '@theme/ReferenceCodeBlock';
import CodeBlock from '@theme-init/CodeBlock';

function hasReferenceMeta(props) {
  return props.reference || props.metastring?.split(' ').includes('reference');
}

const componentWrapper = (Component) => {
  const WrappedComponent = (props) => {
    if (hasReferenceMeta(props)) {
      return <ReferenceCodeBlock {...props} />;
    }

    return <CodeBlock {...props} />;
  };

  return WrappedComponent;
};

export default componentWrapper(CodeBlock);

```

Demo: https://stackblitz.com/edit/github-gfe3e9?file=src%2Fpages%2Findex.md,docusaurus.config.js,src%2Ftheme%2FCodeBlock.js

**Comment by homotechsual** [comment]
That's absolutely amazing - so much more than I'd hoped to get as input :-)

I'll absolutely PR this and a few docs changes I worked on whilst trying to fix this locally :-)

**Comment by christian-bromann** [comment]
Thanks @slorber , I am actually working on fixing this atm.

**Comment by christian-bromann** [comment]
I was able to [update](https://github.com/webdriverio/webdriverio/commit/a2f81bb7f5d43d5168b45923dea69389a216ac9d) the WebdriverIO docs using the latest release. The only we weird thing was that Docusaurus v3 doesn't seem to resolve the theme plugin anymore. I had to make this change:

```patch
- themes: ['docusaurus-theme-github-codeblock'],
+ themes: [path.resolve(__dirname, 'node_modules', 'docusaurus-theme-github-codeblock', 'build', 'index.js')],
```

@slorber is this a confusion on my side or something that actually changed in v3?

**Comment by homotechsual** [comment]
I'm seeing: 

> TypeError: Cannot read properties of undefined (reading 'resolve')
    at Object.getThemePath (R:\Sites\homotechsual\node_modules\docusaurus-theme-github-codeblock\cjs\cjs\index.js:13:36)
    at R:\Sites\homotechsual\node_modules\@docusaurus\core\lib\webpack\aliases\index.js:82:92
    at Array.map (<anonymous>)
    at loadThemeAliases (R:\Sites\homotechsual\node_modules\@docusaurus\core\lib\webpack\aliases\index.js:82:10)
    at createBaseConfig (R:\Sites\homotechsual\node_modules\@docusaurus\core\lib\webpack\base.js:44:63)
    at createClientConfig (R:\Sites\homotechsual\node_modules\@docusaurus\core\lib\webpack\client.js:20:54)
    at Command.start (R:\Sites\homotechsual\node_modules\@docusaurus\core\lib\commands\start.js:92:74)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by christian-bromann** [comment]
@homotechsual please update to `v2.0.1`

**Comment by slorber** [comment]
> I was able to [update](https://github.com/webdriverio/webdriverio/commit/a2f81bb7f5d43d5168b45923dea69389a216ac9d) the WebdriverIO docs using the latest release. The only we weird thing was that Docusaurus v3 doesn't seem to resolve the theme plugin anymore. I had to make this change:
> 
> ```diff
> - themes: ['docusaurus-theme-github-codeblock'],
> + themes: [path.resolve(__dirname, 'node_modules', 'docusaurus-theme-github-codeblock', 'build', 'index.js')],
> ```
> 
> @slorber is this a confusion on my side or something that actually changed in v3?

Hmmm, surprising, is this the only package leading to this behavior?

We replaced "import-fresh" by "jiti" in v3, but I don't think I've seen this issue so far
